# Generated by Django 6.0.2 on 2026-06-07 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
